version: '3'

services:
    web:
        networks:
            - back-tier
networks:
    back-tier:
        driver: overlay
        ipam:
          driver: default
          config:
            - subnet: 11.0.0.0/16
