version: '2'

services:
  web:
    build: .
    ports:
      - "7616:7616"
    volumes:
      - .:/code
    environment:
      - HOST_IP=${HOST_IP}
      - SERVICE_NAME=DiscoveryService
      - STAGE=${STAGE}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
